config:
  credentials: []
  project_repos:
    checkstyles-samples:
      branch: master
      deploy_template: .sqa/docker-compose.yml
      repo: https://github.com/EOSC-synergy/checkstyle-samples
environment: {}
sqa_criteria:
  qc_style:
    repos:
      checkstyles-samples:
        commands:
        - mvn checkstyle:check
        container: maven-testing
        tox:
          testenv: []
          tox_file: ''
