services:
  node:
    command: sleep 6000000
    hostname: sqaaas-web
    image: node
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
